# Generated by Django 3.0.3 on 2020-05-10 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karim', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='date_save',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
