# Generated by Django 2.2.12 on 2020-05-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karim', '0003_auto_20200510_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
