# Generated by Django 2.2.12 on 2020-05-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karim', '0005_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Sites',
        ),
    ]
