# Generated by Django 2.2.12 on 2020-05-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karim', '0006_auto_20200510_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='django_site',
        ),
    ]
