# Generated by Django 2.2.12 on 2020-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karim', '0007_auto_20200510_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
